name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Check npm version
      run: npm --version

    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Clean npm cache
      run: npm cache clean -f

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npx webpack

    - name: Display npm install log
      run: cat /home/runner/.npm/_logs/2024-03-05T10_40_57_945Z-debug.log
